# See https://github.com/netlify/netlify-cms/blob/master/example/config.yml
backend:
  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)

# display_url: https://gatsbro.netlify.com # This url will display in the top-right of the CMS
media_folder: "static/images/uploads" # Media files will be stored in the repo under static/images/uploads
public_folder: "/images/uploads" # The src attribute for uploaded media will begin with /images/uploads

collections: # A list of collections the CMS should be able to edit
  - name: "pages"
    label: "Page"
    delete: false # Prevent users from deleting documents in this collection
    editor:
      preview: true
    files:
      - file: "content/pages/contact.md"
        label: "Contact Page"
        name: "contact-page"
        fields:
          - {label: Template, name: template, widget: hidden, default: ContactPage}
          - {label: Slug, name: slug, widget: hidden, default: 'contact'}
          - {label: Title, name: title, widget: string}
          - {label: Footer Image, name: footerImage, widget: image}
          - label: "Intro"
            name: "intro"
            widget: object
            fields:
              - {label: Large Title, name: largeTitle, widget: string,}
              - {label: Title, name: title, widget: string}
              - {label: Subtitle, name: subtitle, widget: string}
              - {label: Left Column, name: leftColumn, widget: string}
              - {label: Right Column, name: rightColumn, widget: string}
          - label: "Contact Info"
            name: "contactInfo"
            widget: object
            fields:
              - {label: Phone, name: phone, widget: string}
              - {label: Email, name: email, widget: string}
              - {label: Address, name: address, widget: string}
      - file: "content/pages/faq.md"
        label: "FAQ Page"
        name: "faq-page"
        fields:
          - {label: Template, name: template, widget: hidden, default: ContactPage}
          - {label: Slug, name: slug, widget: hidden, default: 'contact'}
          - {label: Title, name: title, widget: string}
          - {label: Hero Image, name: heroImage, widget: image}
          - {label: Footer Image, name: footerImage, widget: image}
          - label: "Intro"
            name: "intro"
            widget: object
            fields:
              - label: "Intro"
                name: "intro"
                widget: object
                fields:
                  - {label: Large Title, name: largeTitle, widget: string,}
                  - {label: Title, name: title, widget: string}
                  - {label: Subtitle, name: subtitle, widget: string}
                  - {label: Left Column, name: leftColumn, widget: string}
                  - {label: Right Column, name: rightColumn, widget: string}
          - label: "Accordion"
            name: "accordion"
            widget: list
            fields:
              - {label: Title, name: title, widget: string}
              - {label: Content, name: content, widget: markdown}

      - file: "content/pages/areas.md"
        label: "Areas Page"
        name: "areas-page"
        fields:
          - {label: Template, name: template, widget: hidden, default: ContactPage}
          - {label: Slug, name: slug, widget: hidden, default: 'contact'}
          - {label: Title, name: title, widget: string}
          - {label: Hero Image, name: heroImage, widget: image}
          - {label: Footer Image, name: footerImage, widget: image}

          - label: "Intro"
            name: "intro"
            widget: object
            fields:
              - {label: Large Title, name: largeTitle, widget: string,}
              - {label: Title, name: title, widget: string}
              - {label: Subtitle, name: subtitle, widget: string}
              - {label: Left Column, name: leftColumn, widget: string}
              - {label: Right Column, name: rightColumn, widget: string}

          - label: "Icon List"
            name: "iconList"
            widget: object
            fields:
              - label: "Left Column"
                name: "left"
                widget: list
                fields:
                  - {label: Icon, name: icon, widget: image}
                  - {label: Title, name: title, widget: string}
                  - {label: Content, name: content, widget: string}
              - label: "Right Column"
                name: "right"
                widget: list
                fields:
                  - {label: Icon, name: icon, widget: image}
                  - {label: Title, name: title, widget: string}
                  - {label: Content, name: content, widget: string}

          - label: "More"
            name: "more"
            widget: object
            fields:
              - {label: Large Title, name: largeTitle, widget: string}
              - {label: Title, name: title, widget: string}
              - {label: Content, name: content, widget: string}
              - {label: Button Text, name: buttonText, widget: string}
              - {label: Button Link, name: buttonLink, widget: string}

      - file: "content/pages/about.md"
        label: "About Page"
        name: "about-page"
        fields:
          - {label: Template, name: template, widget: hidden, default: HomePage}
          - {label: Slug, name: slug, widget: hidden, default: ''}
          - {label: Title, name: title, widget: string}
          - {label: Hero Image, name: heroImage, widget: image}
          - {label: Center Image, name: centerImage, widget: image}
          - {label: Footer Image, name: footerImage, widget: image}

          - label: "About Section"
            name: "about"
            widget: "object"
            fields:
              - {label: Large Title, name: largeTitle, widegt: string, required: false}
              - {label: Title, name: title, widegt: string, required: false}
              - {label: Subtitle, name: subtitle, widegt: string, required: false}
              - {label: Left Column, name: leftColumn, widget: markdown, required: false}
              - {label: Right Column, name: rightColumn, widget: markdown, required: false}

          - label: "Timeline"
            name: "timeline"
            widget: "object"
            fields:
              - label: "Event"
                name: "event"
                widget: "list"
                fields:
                  - {label: Year, name: year, widegt: string, required: false}
                  - {label: Content, name: content, widegt: string, required: false}
              - label: "Event Now"
                name: "eventNow"
                widget: "object"
                fields:
                  - {label: Title, name: title, widegt: string, required: false}
                  - {label: Content, name: content, widegt: string, required: false}

          - label: "Careers Section"
            name: "career"
            widget: "object"
            fields:
              - {label: Large Title, name: largeTitle, widegt: string, required: false}
              - {label: Title, name: title, widegt: string, required: false}
              - {label: Subtitle, name: subtitle, widegt: string, required: false}
              - {label: Left Column, name: leftColumn, widget: markdown, required: false}
              - {label: Right Column, name: rightColumn, widget: markdown, required: false}

          - label: "Work Section"
            name: "work"
            widget: "object"
            fields:
              - {label: Large Title, name: largeTitle, widegt: string, required: false}
              - {label: Title, name: title, widegt: string, required: false}
              - {label: Subtitle, name: subtitle, widegt: string, required: false}
              - {label: Left Column, name: leftColumn, widget: markdown, required: false}
              - {label: Right Column, name: rightColumn, widget: markdown, required: false}
              - label: "Accordion"
                name: accordion
                widget: "list"
                fields:
                  - {label: Title, name: title, widget: string, required: false}
                  - {label: Content, name: content, widget: markdown, required: false}

          - label: "More"
            name: "more"
            widget: object
            fields:
              - {label: Large Title, name: largeTitle, widget: string}
              - {label: Title, name: title, widget: string}
              - {label: Content, name: content, widget: string}
              - {label: Button Text, name: buttonText, widget: string}
              - {label: Button Link, name: buttonLink, widget: string}

      - file: "content/pages/home.md"
        label: "Home Page"
        name: "home-page"
        fields:
          - {label: Template, name: template, widget: hidden, default: HomePage}
          - {label: Slug, name: slug, widget: hidden, default: ''}
          - {label: Title, name: title, widget: string}
          - {label: Opener Image, name: openerImage, widget: image}
          - {label: Footer Image, name: footerImage, widget: image}

          - label: "About"
            name: "about"
            widget: "object"
            fields:
              - {label: Large Title, name: largeTitle, widegt: string, required: false}
              - {label: Title, name: title, widegt: string, required: false}
              - {label: Subtitle, name: subtitle, widegt: string, required: false}
              - {label: Left Column, name: leftColumn, widget: markdown, required: false}
              - {label: Right Column, name: rightColumn, widget: markdown, required: false}

          - label: "Areas"
            name: "areas"
            widget: "object"
            fields:
              - {label: Large Title, name: largeTitle, widegt: string, required: false}
              - {label: Title, name: title, widegt: string, required: false}
              - {label: Subtitle, name: subtitle, widegt: string, required: false}
              - {label: Left Column, name: leftColumn, widget: markdown, required: false}
              - {label: Right Column, name: rightColumn, widget: markdown, required: false}


  - name: "settings"
    label: "Settings"
    delete: false # Prevent users from deleting documents in this collection
    editor:
      preview: false
    files:
      - file: "content/settings/global.yml"
        label: "Global Settings"
        name: "global-settings"
        fields:
          - {label: Site Title, name: siteTitle, widget: string}
          - {label: Site Url, name: siteUrl, widget: string, required: false}
          - {label: Site Description, name: siteDescription, widget: text, required: false}
          - {label: Header Meta / Scripts, name: headerScripts, widget: text, required: false}
          - {label: OpenGraph Card, name: openGraphCard, widget: image, required: false}
